services:
  frontend:
    build: ./frontend
    container_name: ai-quiz-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: ai-quiz-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Adarsh206
      MYSQL_DATABASE: ai_quiz_db
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ai-quiz-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_API_KEY=AIzaSyDR_CpmcMDfhW1GHStfS-L-n4CXONbCFJ4
      - GEMINI_API_KEY=AIzaSyDR_CpmcMDfhW1GHStfS-L-n4CXONbCFJ4
      - DATABASE_URL=mysql+pymysql://root:Adarsh206@db:3306/ai_quiz_db
    ports:
      - "8000:8000"

volumes:
  db_data:
